[ALPSStreamProcessor 2024-10-29 00:00:11] WARNING: a thread raised an Exception, which will be logged as an error below but not re-raised. The thread that raised the error will be restarted.
Traceback (most recent call last):
  File "/srv/hemi01-j01/anaconda3/envs/birdshot/lib/python3.9/site-packages/openmsitoolbox/utilities/exception_tracking_thread.py", line 29, in run
    super().run(*args, **kwargs)
  File "/srv/hemi01-j01/anaconda3/envs/birdshot/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/hemi01-j01/openmsistream/openmsistream/kafka_wrapper/controlled_message_processor.py", line 62, in _run_worker
    self.__do_alive_loop_iteration(consumer)
  File "/srv/hemi01-j01/openmsistream/openmsistream/kafka_wrapper/controlled_message_processor.py", line 100, in __do_alive_loop_iteration
    retval = self._process_message(self.lock, msg)
  File "/srv/hemi01-j01/openmsistream/openmsistream/data_file_io/actor/data_file_stream_processor.py", line 159, in _process_message
    processing_retval = self._process_downloaded_data_file(
  File "/srv/hemi01-j01/original_alpss/ALPSS/containerized_alpss/alpss_stream_processor.py", line 141, in _process_downloaded_data_file
    raise NotImplementedError
NotImplementedError
